async function () {
  const results = [], $ = id => document.getElementById(id);
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const assert = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  async function until(test, label, timeout = 4000) {
    const start = performance.now();
    while (!test()) { if (performance.now() - start > timeout) throw new Error('Timeout: ' + label); await wait(25); }
  }
  function input(id, value) { $(id).value = value; $(id).dispatchEvent(new Event('input', { bubbles: true })); }
  async function go(day) {
    $('dataSelecionada').value = day;
    $('dataSelecionada').dispatchEvent(new Event('change', { bubbles: true }));
    await until(() => !$('pagina').inert && $('numeroPagina').textContent === day.slice(8) + '/' + day.slice(5, 7) + '/' + day.slice(0, 4), 'go ' + day);
  }
  function selectText(row, start, end) {
    const text = row.querySelector('.note-text'), walker = document.createTreeWalker(text, NodeFilter.SHOW_TEXT), nodes = [];
    let node;
    while (node = walker.nextNode()) nodes.push(node);
    function point(offset) { for (const n of nodes) { if (offset <= n.length) return [n, offset]; offset -= n.length; } return [text, text.childNodes.length]; }
    const range = document.createRange(); range.setStart(...point(start)); range.setEnd(...point(end));
    const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  }
  try {
    await until(() => window.__mock && $('tituloData').textContent, 'app initialization');
    const mock = window.__mock;
    assert(!$('telaLogin').hidden && $('aplicativo').hidden, 'login: initial visibility');
    input('emailLogin', 'teste@example.com'); input('senhaLogin', 'incorrect');
    $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => $('mensagemLogin').textContent.includes('incorretos'), 'invalid login');
    assert(!$('btnEntrar').disabled, 'login: error enables retry');
    localStorage.setItem('meu-caderno-diario-v1', JSON.stringify({ '2024-02-29': [{ id: 'legacy', texto: 'Página antiga preservada', cor: '#f3a7d8', concluido: true, criadoEm: 1 }] }));
    input('senhaLogin', 'test-password');
    $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => !$('aplicativo').hidden && $('statusSalvamento').textContent === 'Salvo', 'authenticated snapshot');
    const today = $('dataSelecionada').value;
    assert(!mock.documents.has('users/test-user/caderno/legacy'), 'account isolation: anonymous local notes are not automatically imported (b57aa73)');
    mock.seed('legacy', { data: '2024-02-29', texto: 'Página antiga preservada', cor: '#f3a7d8', concluido: true, criadoEm: 1 });
    assert(mock.subscriptions === 1, 'sync: one active listener');
    mock.seed('first', { data: today, texto: 'Planejar a semana com calma', concluido: false, cor: '#f3a7d8', criadoEm: 2, extraField: 'keep' });
    mock.seed('second', { data: today, texto: 'Uma ideia que merece ficar no papel.', concluido: true, cor: '#fff08c', criadoEm: 3 });
    assert(document.querySelectorAll('.note-row').length === 2, 'sync: snapshot renders existing notes');
    assert($('calendario').querySelector('[data-date="' + today + '"] .cal-dot'), 'calendar: real note indicator');
    const baseWrites = mock.writes.length;
    mock.hold = true;
    input('novoItem', 'Nota única'); $('btnAdicionar').click();
    $('novoItem').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    $('novoItem').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    assert(mock.writes.length === baseWrites + 1, 'save: repeated Enter cannot duplicate pending note');
    input('novoItem', 'Novo rascunho durante o salvamento');
    mock.release(); await until(() => $('statusSalvamento').textContent === 'Salvo', 'pending note saved');
    assert($('novoItem').value === 'Novo rascunho durante o salvamento', 'save: newer draft is preserved');
    input('novoItem', '');
    mock.failNext = true; input('novoItem', 'Texto protegido em caso de erro'); $('btnAdicionar').click();
    await until(() => $('statusSalvamento').dataset.state === 'error', 'save failure');
    assert($('novoItem').value.includes('Texto protegido'), 'save: failure keeps draft');
    $('btnAdicionar').click(); await until(() => !$('novoItem').value, 'retry save');
    assert($('statusSalvamento').textContent === 'Salvo', 'save: retry succeeds');
    let row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'editor opened');
    input('editarItem', 'Planejar a semana com mais calma');
    await until(() => mock.documents.get('users/test-user/caderno/first').texto.includes('mais'), 'debounced autosave');
    assert($('editarItem') && document.activeElement === $('editarItem'), 'editor: snapshot does not steal focus');
    assert(mock.documents.get('users/test-user/caderno/first').extraField === 'keep', 'save: merge preserves unknown fields');
    row.querySelector('[data-action="finish-edit"]').click(); await until(() => !$('editarItem'), 'editor closed');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'reopen editor');
    mock.hold = true;
    input('editarItem', 'Primeira revisão pendente');
    await until(() => $('statusSalvamento').textContent === 'Salvando…', 'pending edit');
    input('editarItem', 'Revisão mais recente preservada');
    $('proximoDia').click(); await wait(100);
    assert($('dataSelecionada').value === today, 'editor: navigation waits for autosave');
    mock.release();
    await until(() => !$('pagina').inert && $('dataSelecionada').value !== today, 'latest edit then navigation');
    assert(mock.documents.get('users/test-user/caderno/first').texto === 'Revisão mais recente preservada', 'editor: typing during pending autosave is persisted before navigation');
    await go(today);
    row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'edit before failure');
    mock.failNext = true; input('editarItem', 'Planejar a semana com mais calma');
    $('proximoDia').click();
    await until(() => $('statusSalvamento').dataset.state === 'error', 'failed navigation save');
    assert($('dataSelecionada').value === today && $('editarItem').value === 'Planejar a semana com mais calma', 'editor: failed save keeps date and unsaved text');
    row.querySelector('[data-action="finish-edit"]').click(); await until(() => !$('editarItem'), 'retry editing');
    assert(!$('listaItens').querySelector('.note-check, [role="checkbox"], [data-action="options"]') && !document.getElementById('i-more'), 'notes: no left checkbox or ellipsis menu');
    assert(!$('progressoDia'), 'notes: no task progress summary');
    const beforeClick = mock.writes.length;
    row.querySelector('.note-text').click(); await wait(30);
    assert(mock.writes.length === beforeClick && [...document.querySelectorAll('.note-context')].every(node => getComputedStyle(node).display === 'flex'), 'notes: actions always visible; clicking text has no side effects');
    row.querySelector('[data-action="toggle"]').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').concluido === true && $('statusSalvamento').textContent === 'Salvo', 'complete');
    assert(row.classList.contains('done') && row.querySelector('[data-action="toggle"]').getAttribute('aria-pressed') === 'true', 'completion: persisted using legacy field and visible feedback');
    row.querySelector('[data-action="toggle"]').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').concluido === false && $('statusSalvamento').textContent === 'Salvo', 'undo completion');
    assert(!row.classList.contains('done'), 'completion: can undo');
    assert($('formAnotacao').compareDocumentPosition($('listaItens')) & Node.DOCUMENT_POSITION_FOLLOWING, 'composer: creation before notes');
    assert(getComputedStyle(row.querySelector('.note-text')).fontFamily.includes('Segoe Print') && !getComputedStyle($('tituloData')).fontFamily.includes('Segoe Print') && !getComputedStyle($('novoItem')).fontFamily.includes('Segoe Print'), 'font: original handwriting only in annotation content');
    const chooseHex = color => { $('abrirPaleta').click(); input('hexCor', color); $('aplicarGrifo').click(); };
    $('abrirPaleta').click(); input('hexCor', '#XYZ123');
    assert($('aplicarGrifo').disabled && $('hexCor').getAttribute('aria-invalid') === 'true', 'picker: invalid HEX cannot be applied');
    input('hexCor', '#19A7CE');
    assert($('previewGrifo').style.getPropertyValue('--highlight') === '#19A7CE' && $('amostraCor').getAttribute('aria-label') === '#19A7CE' && localStorage.getItem('caderno-marker-color') === '#19A7CE', 'picker: preview, top swatch and persisted global color update immediately');
    $('tonalidadeCor').value = '280'; $('tonalidadeCor').dispatchEvent(new Event('input', { bubbles: true }));
    assert($('hexCor').value !== '#19A7CE', 'picker: hue changes color');
    const keyColor = $('hexCor').value;
    $('campoCor').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft', shiftKey: true, bubbles: true, cancelable: true }));
    assert($('hexCor').value !== keyColor, 'picker: saturation adjustable with keyboard');
    input('hexCor', '#19A7CE'); $('aplicarGrifo').click();
    input('novoItem', 'Curta & <segura> "à mão" 🖊'); $('btnAdicionar').click();
    await until(() => !$('novoItem').value, 'creation');
    const created = mock.writes.at(-1);
    assert(created.value.grifos.length === 0 && created.value.concluido === false, 'create: starts without ink or completion despite global color');
    const coloredRow = [...document.querySelectorAll('.note-row')].find(node => node.dataset.id === created.path.split('/').at(-1));
    coloredRow.querySelector('[data-action="mark"]').click();
    await until(() => coloredRow.querySelector('mark') && $('statusSalvamento').textContent === 'Salvo', 'apply global ink');
    assert($('paleta').hidden && coloredRow.querySelector('mark').style.getPropertyValue('--highlight') === '#19A7CE', 'highlight: row applies global color without its own picker');
    assert(coloredRow.querySelector('mark').textContent === 'Curta & <segura> "à mão" 🖊' && !coloredRow.querySelector('segura'), 'render: special characters remain plain text');
    assert(coloredRow.classList.contains('is-marking'), 'highlight: left-to-right stroke on apply');
    await wait(450); mock.emit();
    assert(!coloredRow.classList.contains('is-marking'), 'highlight: snapshots do not replay stroke');
    const writesBeforeColor = mock.writes.length;
    chooseHex('#31A854');
    assert(mock.writes.length === writesBeforeColor && coloredRow.querySelector('mark').style.getPropertyValue('--highlight') === '#19A7CE', 'global: changing default does not write or recolor existing notes');
    coloredRow.querySelector('[data-action="toggle"]').click();
    await until(() => coloredRow.classList.contains('done') && $('statusSalvamento').textContent === 'Salvo', 'complete colored note');
    assert(coloredRow.querySelector('mark').style.getPropertyValue('--highlight') === '#19A7CE', 'completion: ink remains visible with its saved color');
    coloredRow.querySelector('[data-action="mark"]').click();
    await until(() => coloredRow.querySelector('mark').style.getPropertyValue('--highlight') === '#31A854', 'explicit recolor');
    assert(coloredRow.classList.contains('done'), 'highlight: explicit recolor preserves completion');
    chooseHex('#19A7CE'); coloredRow.querySelector('[data-action="mark"]').click();
    await until(() => coloredRow.querySelector('mark').style.getPropertyValue('--highlight') === '#19A7CE' && $('statusSalvamento').textContent === 'Salvo', 'restore fixture ink');
    input('novoItem', 'Anotação sem marca-texto'); $('btnAdicionar').click();
    await until(() => !$('novoItem').value, 'plain creation');
    assert(mock.writes.at(-1).value.grifos.length === 0, 'create: global color is not automatically applied');
    chooseHex('#31A854'); selectText(row, 0, 8);
    row.querySelector('[data-action="mark"]').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').grifos?.length === 1 && $('statusSalvamento').textContent === 'Salvo', 'whole highlight');
    assert(row.querySelector('mark').textContent === row.querySelector('.note-text').textContent, 'highlight: browser selection ignored; entire note uses global color');
    assert(!row.querySelector('.note-context mark, .note-actions mark') && getComputedStyle(row.querySelector('[data-action="mark"]')).userSelect === 'none' && getComputedStyle(row.querySelector('.note-text')).userSelect === 'text', 'highlight: controls are separate and nonselectable; note text remains selectable');
    chooseHex('#E85D75'); selectText(row, 0, 8); row.querySelector('[data-action="mark"]').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').grifos[0].cor === '#E85D75' && $('statusSalvamento').textContent === 'Salvo', 'whole recolor');
    assert(row.querySelectorAll('mark').length === 1 && row.querySelector('mark').textContent === row.querySelector('.note-text').textContent, 'highlight: recolor replaces whole note without stacking');
    await wait(400); row.querySelector('[data-action="mark"]').click();
    await until(() => row.classList.contains('is-marking'), 'same-color animation');
    assert(true, 'highlight: same-color explicit reapply animates once');
    await until(() => !row.querySelector('[data-action="mark"]').disabled, 'reapply settled');
    mock.failNext = true; row.querySelector('[data-action="unmark"]').click();
    await wait(30);
    assert(row.querySelector('mark').getAnimations().some(animation => animation.effect.getTiming().duration === 200), 'highlight: removal retracts ink over 200ms');
    await until(() => $('statusSalvamento').dataset.state === 'error' && !row.querySelector('[data-action="unmark"]').disabled, 'removal failed');
    assert(row.querySelector('mark') && getComputedStyle(row.querySelector('mark')).backgroundSize === '100% 76%', 'highlight: failed removal restores visible ink and allows retry');
    selectText(row, 0, 8); row.querySelector('[data-action="unmark"]').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').grifos.length === 0 && $('statusSalvamento').textContent === 'Salvo', 'remove range');
    assert(!row.querySelector('mark') && row.querySelector('.note-text').textContent === 'Planejar a semana com mais calma', 'highlight: removal clears entire note and keeps text');
    assert(row.querySelector('[data-action="unmark"]').disabled && localStorage.getItem('caderno-marker-color') === '#E85D75', 'highlight: no-ink remove is disabled; global preference unchanged');
    mock.failNext = true; row.querySelector('[data-action="mark"]').click();
    await until(() => $('statusSalvamento').dataset.state === 'error' && !row.querySelector('[data-action="mark"]').disabled, 'apply failed');
    assert(!row.querySelector('mark'), 'highlight: failed apply does not invent saved ink');

    // Same text, distinct IDs: selecting A must never redirect an action on B.
    for (const id of ['duplicate-a', 'duplicate-b', 'duplicate-c']) mock.seed(id, { data: today, texto: 'Texto igual', criadoEm: 7, grifos: [], versaoGrifos: 2, concluido: false });
    const duplicate = id => document.querySelector('[data-id="duplicate-' + id + '"]');
    chooseHex('#53C7C5'); duplicate('a').querySelector('[data-action="mark"]').click();
    await until(() => duplicate('a').querySelector('mark') && $('statusSalvamento').textContent === 'Salvo', 'duplicate A ink');
    chooseHex('#EC6686'); selectText(duplicate('a'), 0, 5);
    const writesBeforeB = mock.writes.length;
    duplicate('b').querySelector('[data-action="mark"] span').click();
    await until(() => duplicate('b').querySelector('mark') && $('statusSalvamento').textContent === 'Salvo', 'duplicate B ink');
    assert(duplicate('a').querySelector('mark').style.getPropertyValue('--highlight') === '#53C7C5' && duplicate('b').querySelector('mark').style.getPropertyValue('--highlight') === '#EC6686' && !duplicate('c').querySelector('mark'), 'highlight: duplicate text uses row ID, three notes retain independent states');
    assert(mock.writes.length === writesBeforeB + 1 && mock.writes.at(-1).path.endsWith('/duplicate-b') && !$('editarItem') && !$('confirmarExclusao').open && !duplicate('b').classList.contains('done') && $('dataSelecionada').value === today, 'events: nested button click writes only target ID without edit, toggle, delete or navigation');
    duplicate('b').querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'edit ink');
    input('editarItem', 'Texto igual atualizado'); duplicate('b').querySelector('[data-action="finish-edit"]').click();
    await until(() => !$('editarItem') && $('statusSalvamento').textContent === 'Salvo', 'append ink text');
    assert(duplicate('b').querySelector('mark').textContent === 'Texto igual atualizado', 'editor: appending text preserves whole-note color');
    duplicate('b').querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'replace ink text');
    input('editarItem', 'Texto igual'); duplicate('b').querySelector('[data-action="finish-edit"]').click();
    await until(() => !$('editarItem') && $('statusSalvamento').textContent === 'Salvo', 'replace ink saved');
    assert(duplicate('b').querySelector('mark').textContent === 'Texto igual' && duplicate('b').querySelector('mark').style.getPropertyValue('--highlight') === '#EC6686', 'editor: replacing text preserves color');
    mock.seed('named-color', { data: today, texto: 'Cor antiga por nome', cor: 'red', concluido: true, criadoEm: 4 });
    mock.seed('missing-color', { data: today, texto: 'Sem cor antiga', concluido: true, criadoEm: 5 });
    mock.seed('legacy-empty-ranges', { data: today, texto: 'Grifo integral antigo', cor: '#F08080', concluido: true, grifos: [], criadoEm: 5 });
    assert(document.querySelector('[data-id="legacy-empty-ranges"] mark'), 'legacy: whole-note ink survives old empty ranges');
    mock.seed('long-note', { data: today, texto: 'Anotação longa: ' + 'palavra '.repeat(16), grifos: [{ inicio: 0, fim: 127, cor: '#000000' }], criadoEm: 6 });
    const namedRow = document.querySelector('[data-id="named-color"]');
    assert(namedRow.classList.contains('done') && !document.querySelector('[data-id="long-note"]').classList.contains('done'), 'legacy: old completion restored and missing flag means unfinished');
    assert(namedRow.querySelector('mark').style.getPropertyValue('--highlight') === '#FF0000' && !document.querySelector('[data-id="missing-color"] mark'), 'legacy: named colors normalized and missing color stays unmarked');
    namedRow.querySelector('[data-action="toggle"]').click();
    await until(() => !namedRow.classList.contains('done') && $('statusSalvamento').textContent === 'Salvo', 'undo legacy completion');
    assert(namedRow.querySelector('mark').style.getPropertyValue('--highlight') === '#FF0000', 'legacy: undoing completion does not remove original ink');
    namedRow.querySelector('[data-action="unmark"]').click();
    await until(() => !namedRow.querySelector('mark') && $('statusSalvamento').textContent === 'Salvo', 'remove legacy ink');
    assert(mock.documents.get('users/test-user/caderno/named-color').cor === 'red', 'legacy: removing ink preserves old color field');
    for (const color of ['#000000','#FFFFFF','#FF0000','#00FF00','#0000FF','#123456','#654321']) chooseHex(color);
    assert(JSON.parse(localStorage.getItem('caderno-recent-colors')).length === 6, 'picker: six most recent colors persisted');
    $('abrirPaleta').click(); document.querySelector('[data-color="#123456"]').click();
    assert($('hexCor').value === '#123456', 'picker: recent color can be reused');
    $('aplicarGrifo').click(); chooseHex('#DF4A73');
    input('novoItem', 'Rascunho de hoje');
    $('proximoDia').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value !== today, 'next day');
    const tomorrow = $('dataSelecionada').value;
    assert($('novoItem').value === '', 'navigation: distinct daily draft');
    $('diaAnterior').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value === today, 'previous day');
    assert($('novoItem').value === 'Rascunho de hoje', 'navigation: previous draft recovered');
    input('novoItem', 'Salvar antes de virar a folha'); mock.hold = true; $('btnAdicionar').click(); $('proximoDia').click();
    await wait(100); assert($('dataSelecionada').value === today, 'navigation: waits for pending creation');
    mock.release(); await until(() => !$('pagina').inert && $('dataSelecionada').value === tomorrow, 'navigation after save');
    assert(mock.writes.at(-1).value.data === today, 'navigation: pending save keeps original date');
    await go('2024-02-29');
    assert(document.querySelector('.note-text').textContent === 'Página antiga preservada', 'legacy: old note and leap date load');
    $('proximoDia').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value === '2024-03-01', 'leap boundary');
    await go(today);
    input('buscaPaginas', 'Página antiga preservada');
    assert($('listaPaginas').querySelectorAll('.page-link').length === 1 && $('listaPaginas').querySelector('[data-date="2024-02-29"]'), 'search: matches actual historical content');
    input('buscaPaginas', '');
    const originalTheme = document.documentElement.dataset.theme;
    $('appearanceMode').value = originalTheme === 'dark' ? 'light' : 'dark';
    $('appearanceMode').dispatchEvent(new Event('change', { bubbles: true }));
    assert(document.documentElement.dataset.theme !== originalTheme && localStorage.getItem('caderno-theme') === document.documentElement.dataset.theme, 'theme: toggle and persistence');
    $('sidebarToggle').click(); assert($('sidebar').inert && $('sidebarToggle').getAttribute('aria-expanded') === 'false', 'sidebar: desktop collapse accessible');
    $('sidebarToggle').click(); $('agendaToggle').click(); assert($('agenda').inert, 'agenda: desktop collapse'); $('agendaToggle').click();
    const beforeDelete = mock.documents.size;
    document.querySelector('[data-id="second"] [data-action="delete"]').click(); await until(() => $('confirmarExclusao').open, 'delete dialog');
    assert(mock.documents.size === beforeDelete && document.activeElement === $('cancelarExclusao'), 'delete: initial click only confirms with safe default focus');
    $('cancelarExclusao').click();
    assert(!$('confirmarExclusao').open && mock.documents.size === beforeDelete, 'delete: cancel preserves document');
    document.querySelector('[data-id="second"] [data-action="delete"]').click(); await until(() => $('confirmarExclusao').open, 'delete dialog again');
    mock.failNext = true; $('excluirConfirmado').click();
    await until(() => !$('excluirConfirmado').disabled, 'delete failure');
    assert($('confirmarExclusao').open && mock.documents.size === beforeDelete && $('erroExclusao').textContent.includes('mantida'), 'delete: failed request retains note, shows inline error and allows retry');
    $('excluirConfirmado').click(); await until(() => mock.documents.size === beforeDelete - 1 && !$('confirmarExclusao').open, 'confirmed delete');
    assert(!document.querySelector('[data-id="second"]'), 'delete: realtime UI updated');
    assert(duplicate('a').querySelector('mark').style.getPropertyValue('--highlight') === '#53C7C5' && duplicate('b').querySelector('mark').style.getPropertyValue('--highlight') === '#EC6686', 'delete: remaining notes retain their independent colors');
    input('novoItem', 'Rascunho privado'); $('btnSair').click(); await until(() => !$('telaLogin').hidden, 'logout');
    assert($('novoItem').value === '' && mock.subscriptions === 0, 'logout: clears drafts and listener');
    input('senhaLogin', 'test-password'); $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => !$('aplicativo').hidden && $('statusSalvamento').textContent === 'Salvo', 'relogin');
    assert(mock.subscriptions === 1 && $('novoItem').value === '', 'relogin: no stale draft or duplicate listeners');
    assert(mock.writes.every(write => !Object.hasOwn(write.value, 'completed') && !Object.hasOwn(write.value, 'checked') && !Object.hasOwn(write.value, 'done')), 'writes: reuse concluido without duplicate status fields');
    assert(mock.writes.every(write => write.path.startsWith('users/test-user/caderno/') && write.options.merge === true), 'Firestore: original collection and merge contract');
    row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'edit before account change');
    mock.hold = true; input('editarItem', 'Edição da primeira conta');
    await until(() => $('statusSalvamento').textContent === 'Salvando…', 'held edit before account change');
    $('proximoDia').click();
    await mock.changeUser({ uid: 'other-user', email: 'other@example.com' });
    mock.seed('first', { data: today, texto: 'Texto da segunda conta', cor: '#f3a7d8', criadoEm: 1 }, 'other-user');
    mock.release(); await wait(550);
    assert($('dataSelecionada').value === today && !mock.writes.some(write => write.path.startsWith('users/other-user/')), 'session: old save cannot navigate or write to new account');
    assert(document.querySelector('.note-text').textContent === 'Texto da segunda conta', 'session: new account keeps its own text');
    await mock.changeUser({ uid: 'test-user', email: 'teste@example.com', displayName: 'Caderno de teste' });
    await until(() => $('statusSalvamento').textContent === 'Salvo', 'restore test account');
    return { ok: true, tests: results.length, results };
  } catch (error) { return { ok: false, tests: results.length, results, error: error.message, stack: error.stack }; }
}
