async function () {
  const results = [], $ = id => document.getElementById(id);
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const assert = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  async function until(test, label, timeout = 4000) {
    const start = performance.now();
    while (!test()) { if (performance.now() - start > timeout) throw new Error('Timeout: ' + label); await wait(25); }
  }
  function input(id, value) { $(id).value = value; $(id).dispatchEvent(new Event('input', { bubbles: true })); }
  async function go(day) {
    $('dataSelecionada').value = day;
    $('dataSelecionada').dispatchEvent(new Event('change', { bubbles: true }));
    await until(() => !$('pagina').inert && $('numeroPagina').textContent === day.slice(8) + '/' + day.slice(5, 7) + '/' + day.slice(0, 4), 'go ' + day);
  }
  function selectText(row, start, end) {
    const text = row.querySelector('.note-text'), walker = document.createTreeWalker(text, NodeFilter.SHOW_TEXT), nodes = [];
    let node;
    while (node = walker.nextNode()) nodes.push(node);
    function point(offset) { for (const n of nodes) { if (offset <= n.length) return [n, offset]; offset -= n.length; } return [text, text.childNodes.length]; }
    const range = document.createRange(); range.setStart(...point(start)); range.setEnd(...point(end));
    const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  }
  try {
    await until(() => window.__mock && $('tituloData').textContent, 'app initialization');
    const mock = window.__mock;
    assert(!$('telaLogin').hidden && $('aplicativo').hidden, 'login: initial visibility');
    input('emailLogin', 'teste@example.com'); input('senhaLogin', 'incorrect');
    $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => $('mensagemLogin').textContent.includes('incorretos'), 'invalid login');
    assert(!$('btnEntrar').disabled, 'login: error enables retry');
    localStorage.setItem('meu-caderno-diario-v1', JSON.stringify({ '2024-02-29': [{ id: 'legacy', texto: 'Página antiga preservada', cor: '#f3a7d8', concluido: true, criadoEm: 1 }] }));
    input('senhaLogin', 'test-password');
    $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => !$('aplicativo').hidden && $('statusSalvamento').textContent === 'Salvo', 'authenticated snapshot');
    const today = $('dataSelecionada').value;
    assert(mock.documents.has('users/test-user/caderno/legacy'), 'migration: existing path and data imported');
    assert(mock.subscriptions === 1, 'sync: one active listener');
    mock.seed('first', { data: today, texto: 'Planejar a semana com calma', concluido: false, cor: '#f3a7d8', criadoEm: 2, extraField: 'keep' });
    mock.seed('second', { data: today, texto: 'Uma ideia que merece ficar no papel.', concluido: true, cor: '#fff08c', criadoEm: 3 });
    assert(document.querySelectorAll('.note-row').length === 2, 'sync: snapshot renders existing notes');
    assert($('calendario').querySelector('[data-date="' + today + '"] .cal-dot'), 'calendar: real note indicator');
    const baseWrites = mock.writes.length;
    mock.hold = true;
    input('novoItem', 'Nota única'); $('btnAdicionar').click();
    $('novoItem').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    $('novoItem').dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
    assert(mock.writes.length === baseWrites + 1, 'save: repeated Enter cannot duplicate pending note');
    input('novoItem', 'Novo rascunho durante o salvamento');
    mock.release(); await until(() => $('statusSalvamento').textContent === 'Salvo', 'pending note saved');
    assert($('novoItem').value === 'Novo rascunho durante o salvamento', 'save: newer draft is preserved');
    input('novoItem', '');
    mock.failNext = true; input('novoItem', 'Texto protegido em caso de erro'); $('btnAdicionar').click();
    await until(() => $('statusSalvamento').dataset.state === 'error', 'save failure');
    assert($('novoItem').value.includes('Texto protegido'), 'save: failure keeps draft');
    $('btnAdicionar').click(); await until(() => !$('novoItem').value, 'retry save');
    assert($('statusSalvamento').textContent === 'Salvo', 'save: retry succeeds');
    let row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'editor opened');
    input('editarItem', 'Planejar a semana com mais calma');
    await until(() => mock.documents.get('users/test-user/caderno/first').texto.includes('mais'), 'debounced autosave');
    assert($('editarItem') && document.activeElement === $('editarItem'), 'editor: snapshot does not steal focus');
    assert(mock.documents.get('users/test-user/caderno/first').extraField === 'keep', 'save: merge preserves unknown fields');
    row.querySelector('[data-action="finish-edit"]').click(); await until(() => !$('editarItem'), 'editor closed');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'reopen editor');
    mock.hold = true;
    input('editarItem', 'Primeira revisão pendente');
    await until(() => $('statusSalvamento').textContent === 'Salvando…', 'pending edit');
    input('editarItem', 'Revisão mais recente preservada');
    $('proximoDia').click(); await wait(100);
    assert($('dataSelecionada').value === today, 'editor: navigation waits for autosave');
    mock.release();
    await until(() => !$('pagina').inert && $('dataSelecionada').value !== today, 'latest edit then navigation');
    assert(mock.documents.get('users/test-user/caderno/first').texto === 'Revisão mais recente preservada', 'editor: typing during pending autosave is persisted before navigation');
    await go(today);
    row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'edit before failure');
    mock.failNext = true; input('editarItem', 'Planejar a semana com mais calma');
    $('proximoDia').click();
    await until(() => $('statusSalvamento').dataset.state === 'error', 'failed navigation save');
    assert($('dataSelecionada').value === today && $('editarItem').value === 'Planejar a semana com mais calma', 'editor: failed save keeps date and unsaved text');
    row.querySelector('[data-action="finish-edit"]').click(); await until(() => !$('editarItem'), 'retry editing');
    assert(!$('listaItens').querySelector('.note-check, [role="checkbox"], [data-action="toggle"], .done'), 'notes: no checkbox, completion action or completed class');
    assert(!$('aplicativo').textContent.includes('concluídas') && !$('progressoDia'), 'notes: no completion summary');
    const beforeClick = mock.writes.length;
    row.querySelector('.note-text').click(); await wait(30);
    assert(mock.writes.length === beforeClick, 'notes: clicking text cannot complete or write');
    assert($('formAnotacao').compareDocumentPosition($('listaItens')) & Node.DOCUMENT_POSITION_FOLLOWING, 'composer: creation before notes');
    assert(getComputedStyle(row.querySelector('.note-text')).fontFamily.includes('Segoe Print') && !getComputedStyle($('tituloData')).fontFamily.includes('Segoe Print') && !getComputedStyle($('novoItem')).fontFamily.includes('Segoe Print'), 'font: original handwriting only in annotation content');
    const chooseHex = color => { input('hexCor', color); $('aplicarGrifo').click(); };
    $('abrirPaleta').click(); input('hexCor', '#XYZ123');
    assert($('aplicarGrifo').disabled && $('hexCor').getAttribute('aria-invalid') === 'true', 'picker: invalid HEX cannot be applied');
    input('hexCor', '#19A7CE');
    assert($('previewGrifo').style.getPropertyValue('--highlight') === '#19A7CE', 'picker: arbitrary HEX updates live preview');
    $('tonalidadeCor').value = '280'; $('tonalidadeCor').dispatchEvent(new Event('input', { bubbles: true }));
    assert($('hexCor').value !== '#19A7CE', 'picker: hue changes color');
    const keyColor = $('hexCor').value;
    $('campoCor').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft', shiftKey: true, bubbles: true, cancelable: true }));
    assert($('hexCor').value !== keyColor, 'picker: saturation adjustable with keyboard');
    chooseHex('#19A7CE');
    input('novoItem', 'Curta & <segura> "à mão" 🖊'); $('btnAdicionar').click();
    await until(() => !$('novoItem').value, 'colored creation');
    const colored = mock.writes.at(-1);
    assert(colored.value.grifos[0].cor === '#19A7CE' && colored.value.grifos[0].fim === colored.value.texto.length, 'create: arbitrary whole-note highlight persisted');
    const coloredRow = [...document.querySelectorAll('.note-row')].find(node => node.dataset.id === colored.path.split('/').at(-1));
    assert(coloredRow.querySelector('mark').textContent === 'Curta & <segura> "à mão" 🖊' && !coloredRow.querySelector('segura'), 'render: special characters remain plain text');
    assert(coloredRow.classList.contains('is-marking'), 'highlight: left-to-right stroke on apply');
    await wait(450); mock.emit();
    assert(!coloredRow.classList.contains('is-marking'), 'highlight: snapshots do not replay stroke');
    $('abrirPaleta').click(); $('removerGrifo').click();
    input('novoItem', 'Anotação sem marca-texto'); $('btnAdicionar').click();
    await until(() => !$('novoItem').value, 'uncolored creation');
    assert(mock.writes.at(-1).value.grifos.length === 0 && $('amostraCor').classList.contains('is-none'), 'create: no highlight is optional and explicit');
    selectText(row, 0, 8); $('abrirPaleta').click();
    assert(!$('paleta').hidden && !$('removerGrifo').disabled, 'highlight: selection opens palette');
    chooseHex('#31A854');
    await until(() => mock.documents.get('users/test-user/caderno/first').grifos?.length === 1, 'partial highlight');
    assert(row.querySelector('mark').textContent === 'Planejar', 'highlight: exact selected substring persisted');
    selectText(row, 0, 8); $('abrirPaleta').click(); chooseHex('#E85D75');
    await until(() => $('paleta').hidden, 'recolor');
    assert(mock.documents.get('users/test-user/caderno/first').grifos[0].cor === '#E85D75', 'highlight: recolor replaces overlapping range');
    selectText(row, 0, 8); $('abrirPaleta').click(); $('removerGrifo').click();
    await until(() => mock.documents.get('users/test-user/caderno/first').grifos.length === 0, 'remove range');
    assert(!row.querySelector('mark'), 'highlight: removing ink keeps note');
    row.querySelector('[data-action="options"]').click();
    assert(getComputedStyle(row.querySelector('.note-tools')).display === 'flex', 'note: discrete options opens edit and marker tools');
    row.querySelector('[data-action="mark"]').click(); chooseHex('#A94DD6');
    await until(() => $('paleta').hidden, 'whole-note ink');
    assert(row.querySelector('mark').textContent === row.querySelector('.note-text').textContent, 'highlight: full text only');
    row.querySelector('[data-action="mark"]').click(); $('removerGrifo').click();
    await until(() => $('paleta').hidden, 'whole-note removal');
    assert(!row.querySelector('mark') && mock.documents.get('users/test-user/caderno/first').concluido === false, 'legacy: color changes never modify completion field');
    mock.seed('named-color', { data: today, texto: 'Cor antiga por nome', cor: 'red', concluido: true, criadoEm: 4 });
    mock.seed('missing-color', { data: today, texto: 'Sem cor antiga', concluido: true, criadoEm: 5 });
    mock.seed('legacy-empty-ranges', { data: today, texto: 'Grifo integral antigo', cor: '#F08080', concluido: true, grifos: [], criadoEm: 5 });
    assert(document.querySelector('[data-id="legacy-empty-ranges"] mark'), 'legacy: whole-note ink survives old empty ranges');
    mock.seed('long-note', { data: today, texto: 'Anotação longa: ' + 'palavra '.repeat(16), grifos: [{ inicio: 0, fim: 127, cor: '#000000' }], criadoEm: 6 });
    const namedRow = document.querySelector('[data-id="named-color"]');
    assert(namedRow.querySelector('mark').style.getPropertyValue('--highlight') === '#FF0000' && !document.querySelector('[data-id="missing-color"] mark'), 'legacy: named colors normalized and missing color stays unmarked');
    namedRow.querySelector('[data-action="mark"]').click(); $('removerGrifo').click();
    await until(() => $('paleta').hidden, 'legacy ink removed');
    assert(!namedRow.querySelector('mark') && mock.documents.get('users/test-user/caderno/named-color').concluido === true && mock.documents.get('users/test-user/caderno/named-color').cor === 'red', 'legacy: explicit empty ranges suppress old ink without destroying fields');
    for (const color of ['#000000','#FFFFFF','#FF0000','#00FF00','#0000FF','#123456','#654321']) { $('abrirPaleta').click(); chooseHex(color); }
    assert(JSON.parse(localStorage.getItem('caderno-recent-colors')).length === 6 && JSON.parse(localStorage.getItem('caderno-recent-colors'))[0] === '#654321', 'picker: six most recent colors persisted');
    $('abrirPaleta').click(); document.querySelector('[data-color="#123456"]').click();
    assert($('hexCor').value === '#123456', 'picker: recent color can be reused');
    $('removerGrifo').click();
    input('novoItem', 'Rascunho de hoje');
    $('proximoDia').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value !== today, 'next day');
    const tomorrow = $('dataSelecionada').value;
    assert($('novoItem').value === '', 'navigation: distinct daily draft');
    $('diaAnterior').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value === today, 'previous day');
    assert($('novoItem').value === 'Rascunho de hoje', 'navigation: previous draft recovered');
    input('novoItem', 'Salvar antes de virar a folha'); mock.hold = true; $('btnAdicionar').click(); $('proximoDia').click();
    await wait(100); assert($('dataSelecionada').value === today, 'navigation: waits for pending creation');
    mock.release(); await until(() => !$('pagina').inert && $('dataSelecionada').value === tomorrow, 'navigation after save');
    assert(mock.writes.at(-1).value.data === today, 'navigation: pending save keeps original date');
    await go('2024-02-29');
    assert(document.querySelector('.note-text').textContent === 'Página antiga preservada', 'legacy: old note and leap date load');
    $('proximoDia').click(); await until(() => !$('pagina').inert && $('dataSelecionada').value === '2024-03-01', 'leap boundary');
    await go(today);
    input('buscaPaginas', 'Página antiga preservada');
    assert($('listaPaginas').querySelectorAll('.page-link').length === 1 && $('listaPaginas').querySelector('[data-date="2024-02-29"]'), 'search: matches actual historical content');
    input('buscaPaginas', '');
    const originalTheme = document.documentElement.dataset.theme;
    document.querySelector('.sidebar [data-theme-toggle]').click();
    assert(document.documentElement.dataset.theme !== originalTheme && localStorage.getItem('caderno-theme') === document.documentElement.dataset.theme, 'theme: toggle and persistence');
    $('sidebarToggle').click(); assert($('sidebar').inert && $('sidebarToggle').getAttribute('aria-expanded') === 'false', 'sidebar: desktop collapse accessible');
    $('sidebarToggle').click(); $('agendaToggle').click(); assert($('agenda').inert, 'agenda: desktop collapse'); $('agendaToggle').click();
    const beforeDelete = mock.documents.size;
    document.querySelector('[data-id="second"] [data-action="delete"]').click(); await until(() => mock.documents.size === beforeDelete - 1, 'delete');
    assert(!document.querySelector('[data-id="second"]'), 'delete: realtime UI updated');
    input('novoItem', 'Rascunho privado'); $('btnSair').click(); await until(() => !$('telaLogin').hidden, 'logout');
    assert($('novoItem').value === '' && mock.subscriptions === 0, 'logout: clears drafts and listener');
    input('senhaLogin', 'test-password'); $('formLogin').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await until(() => !$('aplicativo').hidden && $('statusSalvamento').textContent === 'Salvo', 'relogin');
    assert(mock.subscriptions === 1 && $('novoItem').value === '', 'relogin: no stale draft or duplicate listeners');
    assert(mock.writes.slice(1).every(write => !Object.hasOwn(write.value, 'concluido') && !Object.hasOwn(write.value, 'completed') && !Object.hasOwn(write.value, 'checked')), 'writes: no task-state updates after legacy migration');
    assert(mock.writes.every(write => write.path.startsWith('users/test-user/caderno/') && write.options.merge === true), 'Firestore: original collection and merge contract');
    row = document.querySelector('[data-id="first"]');
    row.querySelector('[data-action="edit"]').click(); await until(() => $('editarItem'), 'edit before account change');
    mock.hold = true; input('editarItem', 'Edição da primeira conta');
    await until(() => $('statusSalvamento').textContent === 'Salvando…', 'held edit before account change');
    $('proximoDia').click();
    await mock.changeUser({ uid: 'other-user', email: 'other@example.com' });
    mock.seed('first', { data: today, texto: 'Texto da segunda conta', cor: '#f3a7d8', criadoEm: 1 }, 'other-user');
    mock.release(); await wait(550);
    assert($('dataSelecionada').value === today && !mock.writes.some(write => write.path.startsWith('users/other-user/')), 'session: old save cannot navigate or write to new account');
    assert(document.querySelector('.note-text').textContent === 'Texto da segunda conta', 'session: new account keeps its own text');
    await mock.changeUser({ uid: 'test-user', email: 'teste@example.com', displayName: 'Caderno de teste' });
    await until(() => $('statusSalvamento').textContent === 'Salvo', 'restore test account');
    return { ok: true, tests: results.length, results };
  } catch (error) { return { ok: false, tests: results.length, results, error: error.message, stack: error.stack }; }
}
