async function () {
  const $ = id => document.getElementById(id), results = [];
  const assert = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  const key = (target, value, shiftKey = false) => target.dispatchEvent(new KeyboardEvent('keydown', { key: value, shiftKey, bubbles: true, cancelable: true }));
  $('sidebarToggle').focus(); $('sidebarToggle').click();
  assert(!$('sidebar').inert && $('workspace').inert && $('sidebar').getAttribute('aria-modal') === 'true', 'mobile: sidebar is modal and background inert');
  const first = $('sidebar').querySelector('button');
  assert(document.activeElement === first, 'mobile: opening drawer focuses first control');
  first.focus(); key(first, 'Tab', true);
  assert(document.activeElement === $('btnSair'), 'mobile: Shift+Tab stays inside drawer');
  key($('btnSair'), 'Tab');
  assert(document.activeElement === first, 'mobile: Tab wraps to first control');
  key(first, 'Escape');
  assert($('sidebar').inert && !$('workspace').inert && document.activeElement === $('sidebarToggle'), 'mobile: Escape closes and restores focus');
  $('agendaToggle').focus(); $('agendaToggle').click();
  assert(!$('agenda').inert && $('workspace').inert && $('agenda').getAttribute('aria-modal') === 'true', 'mobile: calendar drawer opens');
  const day = $('calendario').querySelector('[tabindex="0"]');
  day.focus(); key(day, 'ArrowRight');
  assert(document.activeElement.dataset.date !== day.dataset.date && document.activeElement.closest('#calendario'), 'calendar: keyboard moves between days');
  $('panelBackdrop').click();
  assert($('agenda').inert && !$('workspace').inert && document.activeElement === $('agendaToggle'), 'mobile: backdrop closes and restores focus');
  $('abrirPaleta').click();
  const bounds = $('paleta').getBoundingClientRect();
  assert(bounds.left >= 0 && bounds.right <= innerWidth && bounds.top >= 0 && bounds.bottom <= innerHeight, 'mobile: palette fits viewport on both axes');
  key(document.activeElement, 'Escape');
  assert($('paleta').hidden && document.activeElement === $('abrirPaleta'), 'palette: Escape restores focus');
  $('abrirPaleta').click();
  document.querySelector('.page-heading').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
  assert($('paleta').hidden, 'mobile: outside tap closes picker');
  const row = document.querySelector('.note-row');
  assert([...row.querySelectorAll('.note-context button')].every(button => button.getBoundingClientRect().height >= 40 && parseFloat(getComputedStyle(button).fontSize) >= 12), 'mobile: direct actions visible with readable text and touch height');
  const currentColor = localStorage.getItem('caderno-marker-color');
  row.querySelector('[data-action="unmark"]').click();
  await new Promise(resolve => setTimeout(resolve, 350));
  assert(!row.querySelector('mark') && localStorage.getItem('caderno-marker-color') === currentColor, 'mobile: direct removal clears whole note without changing global color');
  row.querySelector('[data-action="mark"]').click();
  await new Promise(resolve => setTimeout(resolve, 100));
  assert(row.querySelector('mark')?.textContent === row.querySelector('.note-text').textContent && !row.querySelector('.note-context mark'), 'mobile: direct highlight covers content only');
  row.querySelector('[data-action="delete"]').click();
  await new Promise(resolve => setTimeout(resolve, 30));
  const dialog = $('confirmarExclusao'), rect = dialog.getBoundingClientRect();
  assert(dialog.open && rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight, 'mobile: delete confirmation fits viewport');
  $('cancelarExclusao').click();
  assert(!dialog.open && row.isConnected, 'mobile: cancelling delete keeps note');
  return { ok: true, tests: results.length, results };
}
